CartoDB/torque

lib/torque/animator.js, lib/torque/renderer/cartocss_render.js, lib/torque/renderer/point.js, package.json
=> Fixes svg drawing functionality

examples/dual_encode.html, examples/light_bright.html, examples/static_bubble_map.html, examples/static_heat_map.html, examples/static_heat_map_simple.html
=> Example additions

examples/car.html, examples/leaflet.html, examples/navy_leaflet.html, lib/torque/renderer/point.js
=> Makes drawing elements always fallback to rendering points or rectangles

lib/torque/renderer/point.js
=> Empties _icons every time Torque re-preloads them

examples/vendor/carto.js, lib/torque/leaflet/torque.js, lib/torque/renderer/cartocss_render.js, lib/torque/renderer/point.js, lib/torque/renderer/simpleheat.js, lib/torque/renderer/torque_filters.js, package.json
Ref. #79 
We're beginning to add image-filters like those found in Mapnik/Carto. For now, adding colorize-alpha.
cc @javisantana
=> Begins support for image-filters

lib/torque/renderer/cartocss_render.js
It was being halved.
@javisantana
=> Corrects the size of the image asset to renderer

lib/torque/leaflet/torque.js, lib/torque/provider/windshaft.js
=> Substitutes inherited functions from leaflet to own correction

lib/torque/renderer/point.js
ref https://github.com/CartoDB/torque/issues/112
=> Fixes itemstoload negative issue

lib/torque/leaflet/torque.js
=> Clears cache when setCartoCSS is called

doc/API.md
@fdansv 
Added missing method to docs
=> Added torqueLayer.setSQL to docs

lib/torque/provider/windshaft.js, test/provider.windshaft.test.js
=> Adds params to request in torque named maps

doc/API.md
@fdansv 
I found a couple of methods that are missing.
=> Added some missing methods

lib/torque/renderer/point.js
Ref #105 
@rochoa is this an acceptable abstraction?
=> Replaces direct call to document with abstraction

lib/torque/gmaps/torque.js, lib/torque/leaflet/torque.js
As suggested @ #88
@javisantana 
@danicarrion
=> Adds timeToStep() method

lib/torque/leaflet/torque.js
Ref #98 
@javisantana 
@danicarrion
=> Makes getTimeSpan actually return an object

examples/navy_leaflet.html, lib/torque/renderer/point.js
Solves #137 
Before:
Now:
cc @javisantana
=> Fixes points position according to resolution

lib/torque/animator.js
=> Makes sure that animation is paused when steps === one

lib/torque/provider/windshaft.js
=> Do not fix values in the edge

lib/torque/core.js, lib/torque/provider/windshaft.js
=> Optional data type for coordinates in Windshaft provider

lib/torque/renderer/cartocss_render.js
Fixes #155. Super simple fix.
@javisantana
=> Allows for zero marker-fill-opacity

lib/torque/provider/windshaft.js, test/provider.windshaft.test.js
see explanation here: https://github.com/CartoDB/cartodb.js/pull/401
=> add support for maps_api_template

doc/API.md, lib/torque/gmaps/torque.js, lib/torque/leaflet/torque.js
=> Throws error when calling setCartoCSS or setSQL with named maps

lib/torque/core.js, lib/torque/provider/windshaft.js
Ref. #178 - already reviewed by @javisantana.
cc. @ohasselblad
=> Changes value array type to UInt8ClampedArray

NEWS, lib/torque/renderer/cartocss_render.js
=> Limits sprite radius to a maximum of 255

lib/torque/renderer/cartocss_render.js, lib/torque/renderer/point.js
Following up from #181, ref. #40 
This time we're limiting the size of the point sub-canvas, and putting the value in a constant.
cc @javisantana
=> More secure sprite limit

lib/torque/gmaps/CanvasLayer.js
=> Add getOpacity/setOpacity to canvaslayer

LICENSE.txt, Makefile, lib/header.js, package.json
Had a go at this so that versions are easier to identify.
@javisantana
=> Adds script to prepend a version header to uncompressed dists

.travis.yml, lib/torque/animator.js, lib/torque/gmaps/torque.js, test/animator.js, test/provider.windshaft.test.js
Fixes #208 and https://github.com/CartoDB/cartodb.js/issues/631
cc @javisantana
=> Checks if animator is running before resuming it on rescale

lib/torque/provider/filterableJson.js
Adds web workers for tile processing in to the BI provider. Closes https://github.com/CartoDB/cartodb-management/issues/4307
@javisantana
=> Adding web worker support for the BI provider

doc/torque_interaction_methods.md, doc/torque_time_slider.md
we had this missing here
/cc @csobier
=> docs: add timeslider and interaction methods

lib/torque/gmaps/torque.js, lib/torque/leaflet/torque.js
=> fixed ready event when using range rendering

lib/torque/gmaps/torque.js, lib/torque/leaflet/torque.js
CR @javisantana 
Add `pointCount` method required for cartod1b
=> Added pointCount method

doc/getting_started.md
Thanks @javisantana , is this better?
=> wordsmithed how libraries are generated

lib/torque/leaflet/leaflet_tileloader_mixin.js, lib/torque/leaflet/torque.js, lib/torque/renderer/datasource.js, lib/torque/renderer/point.js, package.json
Still needs handling of properties that are left unset because of the pass to async.
=> Turbo-carto support

doc/API.md, doc/getting_started.md, doc/torque_api.md, doc/torque_interaction_methods.md, doc/torque_time_slider.md
=> rebranding

package.json
Setting specific versions for d3 and turbo-carto.
CR: @rochoa 
cc @alonsogarciapablo
=> Pointing to a proper version in turbo-carto and d3 dependencies

lib/torque/renderer/point.js
=> Setting cartocss in internal style

doc/getting_started.md, doc/torque_time_slider.md
@rochoa , minor edits applied, simply to name the Builder as the default tool (instead of the Editor). Do you approve?
=> switched default tool from editor to builder in torque docs

examples/navy_gmaps.html, lib/torque/gmaps/torque.js
Fix #278 and [#1528](https://github.com/CartoDB/cartodb.js/issues/1528)
=> Repair broken reference

lib/torque/leaflet/leaflet_tileloader_mixin.js
Fix https://github.com/CartoDB/support/issues/636
=> Round zoom for flyto float values

lib/torque/renderer/point.js
https://github.com/CartoDB/support/issues/1498
--- 
Check if layer exists to prevent an error. More info [here](https://github.com/CartoDB/support/issues/1498#issuecomment-386035383)
=> Fix time series google map

examples/car.html, examples/data_peek.html, examples/dual_encode.html, examples/examples.json, examples/leaflet_interaction.html, examples/light_bright.html, examples/navy_gmaps.html, examples/navy_leaflet.html, examples/navy_ol.html, examples/render-range_leaflet.html, examples/static_bubble_map.html, examples/static_heat_map.html, examples/static_heat_map_simple.html
Fixes https://github.com/CartoDB/support/issues/1842
=> Update Torque examples

.travis.yml, NEWS, lib/torque/renderer/point.js, package-lock.json, package.json
Avoid uncaught exception 'Error: Image given has not completed loading' while drawing with canvas
=> Avoid uncaught exception 'Error: Image given has not completed loading'
